[package]

name = "ctrlc"
version = "0.1.1"
authors = ["Antti Keränen <detegr@gmail.com>"]
license = "MIT"
keywords = ["ctrlc", "signal", "SIGINT"]
description = "Easy Ctrl-C handler for Rust projects"
homepage = "https://github.com/Detegr/rust-ctrlc"
repository = "https://github.com/Detegr/rust-ctrlc.git"

[dependencies]
libc = "0.1"

[dependencies.lazy_static]
version = "0.1"
optional = true

[features]
default = ["stable"]
nightly = []
stable = ["lazy_static"]
