[package]
name = "ctrlc"
version = "3.1.9"
authors = ["Antti Keränen <detegr@gmail.com>"]
description = "Easy Ctrl-C handler for Rust projects"
documentation = "http://detegr.github.io/doc/ctrlc"
homepage = "https://github.com/Detegr/rust-ctrlc"
keywords = ["ctrlc", "signal", "SIGINT"]
categories = ["os"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Detegr/rust-ctrlc.git"
exclude = ["/.travis.yml", "/appveyor.yml"]
edition = "2018"
readme = "README.md"

[target.'cfg(unix)'.dependencies]
nix = "0.22"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["consoleapi", "fileapi", "handleapi", "namedpipeapi", "synchapi", "winbase", "winerror"] }

[dependencies]
byteorder = "1.4"
lazy_static = "1.4"

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["fileapi", "processenv", "winnt"] }

[features]
termination = []

[[test]]
harness = false
name = "tests"
path = "src/tests.rs"
