[package]

name = "ctrlc"
version = "0.1.0"
authors = ["Antti Keränen <detegr@gmail.com>"]
license = "MIT"
keywords = ["ctrlc", "ctrl", "ctrl-c", "control", "signal", "SIGINT", "SetConsoleCtrlHandler"]
description = "Easy Ctrl-C handler for Rust projects"
homepage = "https://github.com/Detegr/rust-ctrlc"
repository = "https://github.com/Detegr/rust-ctrlc.git"

[dependencies]
libc = "*"

[dependencies.lazy_static]
version = "*"
optional = true

[features]
default = ["stable"]
nightly = []
stable = ["lazy_static"]
